version: "3.9"

services:
  app:
    build: .
    container_name: app
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod

  web:
    build: ./nginx
    container_name: web
    ports:
      # 서버의 8888 포트를 컨테이너의 80(HTTP) 포트로 연결합니다.
      - "8888:80"
      # 서버의 8443 포트를 컨테이너의 443(HTTPS) 포트로 연결합니다.
      - "8443:443"
    depends_on:
      - app
    volumes:
      - ./nginx/certs/divary.pem:/etc/ssl/certs/divary.pem:ro
      - ./nginx/certs/divary.key:/etc/ssl/private/divary.key:ro