spring:

  config:
    name: application

  application:
    name: divary-spring

  profiles:
    active: dev

  # H2 콘솔 설정 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Thymeleaf 설정
  thymeleaf:
    cache: false



server:
  port: 8080

# 로깅 설정
logging:
  level:
    com.divary: DEBUG
